name: IBM Cloud Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * *'

defaults:
  run:
    shell: bash

env:
  IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
  RESOURSE_ID: ${{ secrets.RESOURSE_ID }}
  IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
  V2_ID: ${{ secrets.V2_ID }}
  V2_PATH: ${{ secrets.V2_PATH }}
  ALTER_ID: ${{ secrets.ALTER_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          ./deploy.sh
